version: "3"
services:
  backend:
    restart: always
    build: ./todolist_backend/.
    ports: 
      - "9020:9020"
    environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://todo-mysql-test.c2cbv6ov8nd5.ap-northeast-2.rds.amazonaws.com:3306/TEST?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=utf8&autoReconnection=true
            SPRING_DATASOURCE_USERNAME: user
            SPRING_DATASOURCE_PASSWORD: password
    networks: 
      - todo-net

  frontend:
    restart: always
    build: ./todolist-frontend/.
    ports: 
      - "80:80"
    depends_on:
      - backend
    networks: 
      - todo-net
    
networks: 
  todo-net:


    
    ## docker-compose 기본 명령어

    # docker-compose ps                 : 컨테이너 조회 (컴포즈 파일 문제 있으면 조회도 안됨)

    # docker-compose up -d              : 컨테이너 없으면 빌드 하면서 실행 
    # docker-compose up -d --build      : 컨테이너 새롭게 빌드 하면서 실행 (변경사항 있을때 사용)
   
    # docker-compose down               : 컨테이너 내리면서 삭제까지 함께 진행
    # docker-compose stop               : 컨테이너 그냥 중지


    # docker-compose logs -f            : 컨테이너들의 로그를 계속해서 읽기
    # docker rmi -f $(docker ps -a -q)  : 이미지 전체 삭제