server:
  port: 9020
spring:
  datasource:
    url: jdbc:mysql://todo-mysql-test.c2cbv6ov8nd5.ap-northeast-2.rds.amazonaws.com:3306/TEST?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=utf8&autoReconnection=true
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true